spring.application.name=demo
spring.jpa.hibernate.ddl-auto=update
MicrosoftAppId=e7e38ff3-11fa-44e6-88cd-a2bcc5726986
MicrosoftAppPassword=
MicrosoftAppTenantId=f94bf4d9-8087-4794-adf6-a5466ca28563
MicrosoftAppType=UserAssignedMSI